### ISSUE TITLE
Different cursor icons should be added

### ISSUE THREAD

**Issue by caseydierking** [caseydierking/wcss#1]
Buttons should be added somewhere to switch between different cursors. Example: Pitchfork or Hay.

Bonus points if soundbites accompany them and you can interact with the horse.

**Comment by whitneyrosenberg** [comment]
Do you have images for your different cursors?

**Comment by caseydierking** [comment]
Hi whitney, thanks for taking a look here. I don't have any picked out, so feel free to find something that works/fits the theme of the site. Were really just out to have fun with this, so I'd say just give it a whirl.

**Comment by shaileshshivam** [comment]
Can I work on this ?

**Comment by caseydierking** [comment]
@shaileshshivam Check the other issues we have.

**Comment by thalaeg** [comment]
Perhaps a few more could be added. Maybe like a pumpkin for october?
