### ISSUE TITLE
When pressing the space bar, have the horse wink

### ISSUE THREAD

**Issue by thalaeg** [caseydierking/wcss#17]
Have the horse wink when the space bar is pressed. Perhaps a twinkle in the eye would be cool too?

**Comment by adsingh14** [comment]
I will add that feature. :)

**Comment by adsingh14** [comment]
> I will wait excitedly.

https://github.com/caseydierking/wcss/pull/29/commits/b4c83353f2f9a8363d86c4e5629aeb9a29cf7d10

**Comment by caseydierking** [comment]
Closed. See #29
