### ISSUE TITLE
Have the horse randomly poop

### ISSUE THREAD

**Issue by thalaeg** [caseydierking/wcss#18]
Just a small poop randomly. This will be part of a bigger project to keep track of how many items the horse eats relative to the poop. 

Also, we want the pitchfork to eventually clean up the poop.

**Comment by ronlaniado** [comment]
I'll give this a try

**Comment by ronlaniado** [comment]
How exactly would you want it done?

**Comment by agnieszka-miszkurka** [comment]
Can I take this? 😆

**Comment by caseydierking** [comment]
Just following up. @agnieszka-miszkurka you killed it on this. Thanks!
