### ISSUE TITLE
The hay and pitchforks need animations.

### ISSUE THREAD

**Issue by thalaeg** [caseydierking/wcss#20]

**Comment by kev1nboer** [comment]
I can do this! Is that OK?

**Comment by thalaeg** [comment]
Well we were thinking of the clicking animation. But if you have an idea for the right side, that would be cool too!

**Comment by kev1nboer** [comment]
Oh alright. I'll create a pull request so you can see!

**Comment by kev1nboer** [comment]
See #23.

**Comment by thalaeg** [comment]
Hi @kev1nboer , are you still planning on make a few changes to the animations for the hay and pitchfork?
