### ISSUE TITLE
Contribute New Ideas

### ISSUE THREAD

**Issue by caseydierking** [caseydierking/wcss#21]
This would be a great first time issue for someone.
What we really need is is someone to add a file to the root directory and come up with some fun and ridiculous ideas to add to this project. 

We will comb through those ideas and add them as issues to be done. We'll accept pull requests for this file though to have a long running list of ideas.

**Comment by highskillzz** [comment]
What kind of ideas are you guys looking for?

Like games, new tech, AR , VR......?

**Comment by highskillzz** [comment]
What kind of ideas are you guys looking for?

Like games, new tech, AR , VR......?

**Comment by thalaeg** [comment]
We want to involve our favorite pony, Winning Colors Splish Splash. Other than that, we want obtainable ideas that sound like fun to work on.

**Comment by caseydierking** [comment]
Implementing any kind of game component would be ridiculously cool.
