### ISSUE TITLE
Make the horse move with arrow keys

### ISSUE THREAD

**Issue by thalaeg** [caseydierking/wcss#26]
Animate the horse movement (doesn't have to be pretty!) and have the screen move in the background (2D) when the user presses different arrow keys!

**Comment by nm-t** [comment]
This sounds fun! I'll have a look at this.

**Comment by nm-t** [comment]
@thalaeg okay this is incredibly difficult, BUT I'm converting the horse into an SVG so that someone can animate this in the future!

**Comment by crisner** [comment]
I would like to work on this.

**Comment by crisner** [comment]
@thalaeg Does the horse have to move on key press or is it going to be in a loop as soon as the page loads?

**Comment by thalaeg** [comment]
@crisner I was thinking when we press an arrow key. One contributor have converted the image to an svg so it will be easier to animate!

**Comment by thalaeg** [comment]
If you would like to make a two-D field (think old zelda/pokemon) that the horse can move around in, that would be wild too. Like have a button that would go to a seperate page that did that.

**Comment by thalaeg** [comment]
Ultimately both would be in our vision. The left and right movements for the main screen. And a spritesheet for the up and down ones. Whichever sounds most fun to you, go for! If you wanna tackle both, thats even better.

**Comment by caseydierking** [comment]
@crisner . I think creating a sprite kit for this would be perfect. Would love if you could tackle that!

**Comment by caseydierking** [comment]
@crisner , specifically for the sprite kit, i created a new issue #39 if you are interested in taking that.

**Comment by crisner** [comment]
@caseydierking I haven't created a spritekit from scratch before. I'll give it some time and if the issue is still unassigned i'll give it a try. I shall update my status on the issue before the end of day.

**Comment by adsingh14** [comment]
Any space for me to work on this functionality ? :neutral_face:

**Comment by caseydierking** [comment]
@adsingh14 maybe you could get in touch with the guy from #55. He hasn't submitting anything but seems like he has a good starting point for it.

**Comment by caseydierking** [comment]
This has been integrated.
