### ISSUE TITLE
Make the site responsive

### ISSUE THREAD

**Issue by caseydierking** [caseydierking/wcss#32]
With many of the changes from hacktoberfest, the site is really coming along. With these new changes though, it's starting to break when viewed on mobile. Think of the scenario.... you are out with your friends and you want to share this new encouraging website with all your peers. Currently, we can't do that. 

We would like to think through how to make the toolbar work on mobile so you can do all of the same actions on your phone. This will impact other areas like the recent pull request #30 where it looks for the relative position of the horses mouth.

tl,dr; Make the site more responsive than it is now. Toolbar should scale below image and be usable.

**Comment by RuhanRK** [comment]
I am working for it.

**Comment by thalaeg** [comment]
Hi @RuhanRK , this should be easier now as we have an svg for an image
