### ISSUE TITLE
Create a spritekit for the horse

### ISSUE THREAD

**Issue by caseydierking** [caseydierking/wcss#39]
We need to create a spritekit for the horse. Something like this: 
https://opengameart.org/content/lpc-horses-rework

**Comment by crisner** [comment]
@caseydierking Do I use the same horse from the assets for the sprite-sheet? Once this is confirmed I can start planning on creating the the front and back view and the other frames.

**Comment by caseydierking** [comment]
I'd use the horse that we have currently on the site. Does that make sense?

**Comment by crisner** [comment]
I have added the horse sprite for left and right walk cycle in the PR #50 .

**Comment by caseydierking** [comment]
Closed. Good work!
