### ISSUE TITLE
Add hacktoberfest text or badge to website

### ISSUE THREAD

**Issue by caseydierking** [caseydierking/wcss#5]
Let's make this the official hacktoberfest horse. Add a badge or text somewhere on the page that would make us proud.

**Comment by ofarukcaki** [comment]
Hi,

What you meant by badge? Logo or?

**Comment by olvrb** [comment]
I could take this. I am guessing a simple badge will do.

**Comment by olvrb** [comment]
Created PR: #16.

**Comment by ofarukcaki** [comment]
@olvrb why did you stole my pr? omg

**Comment by thalaeg** [comment]
Sorry Omer. We are not going with his PR. But perhaps you can think of something else great to do to Winning Colors!
