### ISSUE TITLE
Make it look like horse is walking left or right

### ISSUE THREAD

**Issue by caseydierking** [caseydierking/wcss#55]
Due to a recent contribution, we have a left and right sprite kit that was added for the horse. It would be cool to have the horse animate and give the impression of walking left when holding the "left" arrow key. Similarly, it would be great to have the horse walk right when holding the "right" arrow key.

**Comment by conanak99** [comment]
I'll take this. Is that fine?

**Comment by conanak99** [comment]
First look. Is that fine?

![https://media.giphy.com/media/57Y7AizfghLdAkLq56/giphy.gif](https://media.giphy.com/media/57Y7AizfghLdAkLq56/giphy.gif)

I'm using background-image for animation, the size is fixed so seems like we need to use `transform: scale` to make it smaller. I'll create a pull request later.

**Comment by caseydierking** [comment]
Great first stab at this. This is what I had envisioned. One thing to consider is which way the horse is left facing after holding down the arrow keys. Another consideration is the area that is determined to be the horses "mouth". And how this change affects that. The horse can eat certain food items only near its mouth.

Just a few thoughts. Great work and quick turnaround!
