### ISSUE TITLE
[NOTE] Need of well written Documentation !

### ISSUE THREAD

**Issue by adsingh14** [caseydierking/wcss#67]
Like other repos, this one is also going in better direction. 

We need a documentation a.k.a. a proper README.md for contributors.

**Comment by caseydierking** [comment]
I agree. This would be a good thing to have.

**Comment by adsingh14** [comment]
Draft 1 -  https://github.com/caseydierking/wcss/pull/68

**Comment by caseydierking** [comment]
@adsingh14 I pulled this in. However, formatting seems weird. Wanna take a look at this and fix it?

**Comment by adsingh14** [comment]
Fixed https://github.com/caseydierking/wcss/pull/70/commits/47f6e997db01b847986dba251103458b42bcdab7

🙂

**Comment by adsingh14** [comment]
@caseydierking Doc still not standardized accoirding to  [Community Section](https://github.com/caseydierking/wcss/community)

**Comment by adsingh14** [comment]
@caseydierking Doc still not standardized according to [Community Section](https://github.com/caseydierking/wcss/community)

**Comment by caseydierking** [comment]
@adsing14 maybe you could open a new issue then to work on getting all those checkboxes green. I thought this issue was referencing just the readme.

**Comment by adsingh14** [comment]
We can make checkbox green using **emoji** where the grey-colored checkbox are styled under [Github Flavored Markdown](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) 'Task Lists' documentation which is easy to implement for all users.
