### ISSUE TITLE
Utilize Animate.css to add some nice animations to toolbar click

### ISSUE THREAD

**Issue by caseydierking** [caseydierking/wcss#71]
I recently added animate.css to the project. I started working on this, but then decided it would be a good first issue for someone.

If you go to the javascript file, you can see that i've commented out 
` //  el.classList.remove('animated');
       // `el.classList.remove('tada');``

What would be great is if when you clicked any of the buttons on the toolbar it would animate by adding the css classes "animated" and "tada". It should also work on the "dark mode" button as well. You'll notice that this is handled a little bit differently currently in the code. 

Animate.css is already included in the project, so all you'd really need to do is make it work in the JS.

**Comment by adsingh14** [comment]
This PR will solve that issue, watch out for click-counter animation --> https://github.com/caseydierking/wcss/issues/69#issuecomment-429472074
