### ISSUE TITLE
Fix/Improve sprite animation

### ISSUE THREAD

**Issue by caseydierking** [caseydierking/wcss#78]
When you click "Let's Play a Game" it activates the mini game functionality. You can then move the horse around with arrow keys.

Currently its buggy and blinks quite a bit. Would be great if someone could take a look at the animation and make it more fluid.

**Comment by hiby90hou** [comment]
I will try to solve this problem

**Comment by adsingh14** [comment]
@caseydierking Have a look on gallop func. - https://github.com/caseydierking/wcss/pull/91
